// Category list for Create Article page
export const CATEGORIES = [
  // 🌍 History & Society
  "Colonialism",
  "Postcolonial Studies",
  "Imperialism",
  "Nationalism",
  "Globalization",
  "Migration & Diaspora",
  "Slavery & Abolition",
  "War & Conflict",
  "Human Rights",
  "Social Movements",
  // 🧠 Philosophy & Thought
  "Existentialism",
  "Marxism",
  "Feminism",
  "Queer Theory",
  "Postmodernism",
  "Structuralism",
  "Ethics & Morality",
  "Philosophy of Religion",
  "Critical Race Theory",
  "Philosophy of Science",
  // 📚 Literature & Arts
  "Classical Literature",
  "Modernism",
  "Poetry",
  "Drama & Theatre",
  "Visual Arts",
  "Film Studies",
  "Music Theory",
  "Cultural Studies",
  "Folklore & Mythology",
  "Graphic Novels",
  // 💻 Technology & Innovation
  "Artificial Intelligence (AI)",
  "Machine Learning",
  "Robotics",
  "Quantum Computing",
  "Blockchain",
  "Cybersecurity",
  "Biotechnology",
  "Nanotechnology",
  "Cloud Computing",
  "Augmented & Virtual Reality",
  // 📊 Economics & Politics
  "Capitalism",
  "Socialism",
  "Political Theory",
  "International Relations",
  "Development Studies",
  "Environmental Economics",
  "Public Policy",
  "Economic History",
  "Global Trade",
  "Political Philosophy",
  // 🌱 Environment & Sustainability
  "Climate Change",
  "Renewable Energy",
  "Environmental Justice",
  "Conservation",
  "Urban Sustainability",
  "Agriculture & Food Systems",
  "Ocean Studies",
  "Indigenous Environmental Knowledge",
  "Ecology",
  "Circular Economy",
  // 🧬 Science & Health
  "Genetics",
  "Neuroscience",
  "Psychology",
  "Medicine & Public Health",
  "Epidemiology",
  "Astrophysics",
  "Chemistry",
  "Biology",
  "Space Exploration",
  "Cognitive Science",
  // 🕌 Religion & Spirituality
  "Islam",
  "Christianity",
  "Judaism",
  "Buddhism",
  "Hinduism",
  "Indigenous Religions",
  "Mysticism",
  "Comparative Religion",
  "Philosophy of Religion",
  "Secularism",
  // 👥 Culture & Identity
  "Race & Ethnicity",
  "Gender Studies",
  "Sexuality",
  "Popular Culture",
  "Media Studies",
  "Digital Cultures",
  "Global South Studies",
  "Youth Culture",
  "Disability Studies",
  "Language & Linguistics",
  // 🚀 Future & Society
  "Transhumanism",
  "Space Colonization",
  "Future of Work",
  "Ethics of AI",
  "Smart Cities",
  "Digital Rights & Privacy",
  "Bioethics",
  "Human Augmentation",
  "Techno-Utopianism",
  "Surveillance Capitalism"
];
